---
# Load a variable file based on the OS type, or a default if not found.
- include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version | int}}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "default.yml"
  when: apache_pkgname is not defined

- name: Installs apache web server
  package: 
    name: "{{ apache_pkgname }}"
    state: present
  notify:
    - enable apache 
    - start apache

- name: Upload default index.html for host
  copy: src=default-apache-index.html dest=/var/www/html/index.html mode=0644
  ignore_errors: True
