---
#--For this playbook - only run either "apache-ssl" OR "apachessl-le" (letsencrypt certs) NOT both!!
- hosts: myawswebservers
  roles:
    - common
    - apache
    #- apache-ssl
    - apache-ssl-le