---
#--For this playbook - only run either "apache-ssl" OR "apachessl-le" (letsencrypt certs) NOT both!!
- name: provision aws ami
  hosts: all
  remote_user: ubuntu
  gather_facts: false
  # - ubuntu 16.04 - needs this since python2 is not installed by default
  pre_tasks:
    - raw: test -e /usr/bin/python || (ln -s /usr/bin/python3 /usr/bin/python)
  roles:
    - common
    - apache
    #- apache-ssl
    #- apache-ssl-le